# Generated by Django 5.0.2 on 2024-05-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_name",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=128,
                        null=True,
                        verbose_name="Service name",
                    ),
                ),
                (
                    "jwt_token",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=500,
                        null=True,
                        verbose_name="JWT token",
                    ),
                ),
                ("service_url", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
