# Generated by Django 5.0.2 on 2024-05-03 14:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("short_name", models.CharField(max_length=512)),
                ("domain_url", models.URLField(default="", max_length=512)),
                ("password_reset_uri", models.URLField(default="", max_length=512)),
            ],
            options={
                "verbose_name": "company",
                "verbose_name_plural": "Companies",
                "db_table": "company",
            },
        ),
    ]
